INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_1','Arts and Crafts Supplies',NULL);
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_2','Baby and Child Products',NULL);
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_3','Clothing',NULL);
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_4','Apparel Accessories','TYPE_3');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_5','Baby and Childrenswear','TYPE_3');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_6','Footwear','TYPE_3');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_7','Handbags, Purses and Wallets','TYPE_3');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_8','Jewelry and Watches','TYPE_3');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_9','Luggage and Travel Bags','TYPE_3');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_10','Menswear','TYPE_3');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_11','Sportswear','TYPE_3');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_12','Womenswear','TYPE_3');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_13','Workwear','TYPE_3');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_14','Consumer Electronics',NULL);
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_15','Audio Equipment','TYPE_14');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_16','Cameras and Camera Equipment','TYPE_14');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_17','Car Electronics and GPS','TYPE_14');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_18','Computer Accessories','TYPE_14');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_19','Desktop Computers and Monitors','TYPE_14');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_20','Laptops and Notebooks','TYPE_14');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_21','Lighting Equipment','TYPE_14');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_22','Smartphones and Mobile Devices','TYPE_14');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_23','Tablets and E-Readers','TYPE_14');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_24','Televisions and Television Services','TYPE_14');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_25','Video Games and Consoles','TYPE_14');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_26','Wearable Technology','TYPE_14');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_27','Consumer Services',NULL);
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_28','Fitness Centers and Health Clubs','TYPE_27');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_29','Florists','TYPE_27');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_30','Funeral Services','TYPE_27');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_31','Hair and Beauty Services','TYPE_27');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_32','Interior Design and Decorative Arts','TYPE_27');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_33','Landscaping Services','TYPE_27');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_34','Laundromats and Dry Cleaners','TYPE_27');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_35','Pet Care and Services','TYPE_27');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_36','Photography Services','TYPE_27');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_37','Household',NULL);
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_38','Do It Yourself','TYPE_37');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_39','Furniture','TYPE_37');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_40','Beds and Bedding','TYPE_39');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_41','Chairs and Seats','TYPE_39');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_42','Office Furniture','TYPE_39');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_43','Gardening Supplies and Equipment','TYPE_37');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_44','Home Security and Safety','TYPE_37');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_45','Household Appliances','TYPE_37');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_46','Household Cleaners','TYPE_37');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_47','Air Fresheners','TYPE_46');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_48','Laundry Care and Detergents','TYPE_46');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_49','Office Supplies and Equipment','TYPE_37');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_50','Stationery and Greeting Cards','TYPE_49');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_51','Pest Control Products','TYPE_37');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_52','Personal Care Products',NULL);
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_53','Baby Care Products','TYPE_52');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_54','Cosmetics','TYPE_52');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_55','Depilatories','TYPE_52');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_56','Eye Care and Eyewear','TYPE_52');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_57','Feminine Hygiene Products','TYPE_52');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_58','Fragrances','TYPE_52');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_59','Deodorants and Anti Perspirants','TYPE_58');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_60','Hair Care Products','TYPE_52');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_61','Men''s Grooming Products','TYPE_52');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_62','Oral Care Products','TYPE_52');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_63','Skin Care Products','TYPE_52');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_64','Sun Care Products','TYPE_63');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_65','Soap, Bath and Shower Products','TYPE_52');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_66','Sporting Goods and Equipment',NULL);
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_67','Angling and Hunting Equipment','TYPE_66');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_68','Bikes and Cycling Equipment','TYPE_66');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_69','Golf Equipment','TYPE_66');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_70','Tennis and Racket Sports Equipment','TYPE_66');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_71','Toys',NULL);
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_72','Beverage',NULL);
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_73','Alcoholic Beverages','TYPE_72');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_74','Beer','TYPE_73');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_75','Brandy','TYPE_73');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_76','Cider','TYPE_73');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_77','Wine','TYPE_73');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_78','Spirits','TYPE_73');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_79','Gin','TYPE_78');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_80','Rum','TYPE_78');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_81','Tequila','TYPE_78');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_82','Vodka','TYPE_78');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_83','Whiskey','TYPE_78');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_84','Bottled Water','TYPE_72');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_85','Hot Drinks','TYPE_72');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_86','Coffee','TYPE_85');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_87','Tea','TYPE_85');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_88','Juice','TYPE_72');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_89','Soft Drinks','TYPE_72');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_90','Sport, Energy and Functional Drinks','TYPE_72');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_91','Food',NULL);
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_92','Baby Food','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_93','Baked Goods','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_94','Breakfast Cereals','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_95','Canned Food','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_96','Cereals, Grains and Pulses','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_97','Condiments and Dressings','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_98','Dairy Products','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_99','Butter','TYPE_98');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_100','Cheese','TYPE_98');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_101','Milk and Cream','TYPE_98');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_102','Yogurt','TYPE_98');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_103','Desserts','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_104','Fast Food and Take Out','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_105','Fish and Seafood','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_106','Frozen Food','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_107','Ice Cream','TYPE_106');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_108','Fruit and Vegetables','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_109','Health Food and Sports Nutrition','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_110','Nutraceuticals and Weight Loss','TYPE_109');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_111','Jellies, Preserves and Spreads','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_112','Meat, Poultry and Eggs','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_113','Nuts, Seeds and Dried Fruit','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_114','Oils and Fats','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_115','Organic Foods','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_116','Pasta and Noodles','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_117','Pet Food','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_118','Pizza','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_119','Processed Food','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_120','Rice and Rice Products','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_121','Snacks and Confectionery','TYPE_91');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_122','Chocolate and Cocoa Products','TYPE_121');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_123','Savory Snacks','TYPE_121');
INSERT INTO Product_Type(Product_Type_id,description,parent_product_type_id) VALUES ('TYPE_124','Soup','TYPE_91');