INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_1','Baumbach, Brekke and Torphy');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_2','Dietrich-Quitzon');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_3','Marquardt-McClure');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_4','Casper and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_5','Cole-White');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_6','Crona-Osinski');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_7','Stark Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_8','Mosciski and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_9','Aufderhar, Boyer and Glover');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_10','Schneider, Friesen and Abshire');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_11','Hane-Vandervort');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_12','Douglas and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_13','Franecki, Hermiston and Medhurst');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_14','Rolfson-Mosciski');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_15','Cronin Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_16','Rolfson, Hammes and Berge');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_17','Hand, Metz and Beahan');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_18','Hoeger Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_19','Williamson Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_20','Hudson and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_21','Borer and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_22','Hoeger LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_23','Koelpin, Conn and Willms');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_24','Ratke Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_25','Turcotte, Ward and Pfeffer');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_26','Torp and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_27','Schoen, Blanda and Spencer');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_28','Lynch, Thompson and Hirthe');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_29','McKenzie Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_30','Steuber, Wiegand and Rutherford');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_31','Herman Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_32','Torphy LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_33','Heller-Waelchi');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_34','Rowe-Heathcote');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_35','Quitzon-Muller');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_36','Heller-Gleason');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_37','Kihn, Swift and Wyman');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_38','Bogisich, Pfeffer and Bogan');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_39','Bode Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_40','Auer, DuBuque and Hamill');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_41','Olson and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_42','Rohan and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_43','Langosh Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_44','Wilderman-Willms');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_45','Ryan, Cremin and Weber');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_46','Beahan-Kertzmann');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_47','Hintz Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_48','West-Wunsch');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_49','Kub LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_50','Sporer-Lind');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_51','Volkman, Murphy and Conroy');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_52','Swift Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_53','Hackett-Christiansen');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_54','Bergnaum-Wuckert');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_55','Schimmel LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_56','Koss-Doyle');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_57','Kihn Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_58','Ratke-Marquardt');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_59','Wilderman, Runolfsson and Christiansen');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_60','Balistreri and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_61','Hills LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_62','Jenkins, Will and Collins');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_63','Bruen LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_64','Daugherty, Langworth and Schmidt');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_65','Skiles, Turcotte and Runolfsdottir');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_66','Barrows, Schoen and Conn');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_67','Murray, Wyman and Fahey');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_68','Ernser Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_69','Bartoletti-Cole');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_70','Rowe-MacGyver');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_71','Weissnat Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_72','Robel-Braun');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_73','Nolan, Sporer and O''Kon');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_74','Stoltenberg and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_75','Pouros-Jones');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_76','Gaylord-Legros');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_77','Emard Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_78','Haley, Pfannerstill and Abbott');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_79','Murray Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_80','Kirlin, Schinner and Daniel');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_81','Schmeler-McKenzie');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_82','Lemke-Feest');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_83','Hamill-Oberbrunner');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_84','Balistreri-Howell');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_85','Rosenbaum-Daniel');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_86','Mohr-Homenick');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_87','Jacobson, Heller and Auer');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_88','West Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_89','Little Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_90','Batz LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_91','Jacobi, Schimmel and Legros');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_92','Williamson-Osinski');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_93','Morar, Wiza and Kihn');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_94','Schamberger-Collins');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_95','West, Conroy and Hintz');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_96','Parisian LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_97','Witting Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_98','Swift, Homenick and Koch');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_99','Spencer-Schimmel');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_100','McGlynn LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_101','Terry-Walter');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_102','Johns-Waters');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_103','Hoppe, Lowe and Stark');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_104','Jakubowski-Kuhn');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_105','Rowe and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_106','Raynor, Lesch and Kerluke');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_107','Waelchi-Herzog');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_108','Glover LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_109','Gleichner-Funk');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_110','West and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_111','Beahan and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_112','Nolan-Mante');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_113','Bailey-Connelly');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_114','Skiles LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_115','Reichert, Ratke and Kunze');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_116','Jaskolski, White and Corkery');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_117','Heathcote, King and Carroll');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_118','Hand-Huel');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_119','Medhurst, Keebler and Gibson');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_120','Gibson LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_121','Ratke, Haley and Beier');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_122','Ratke LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_123','Wehner, Trantow and Wilderman');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_124','Larson Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_125','Little, Gulgowski and Gusikowski');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_126','Gerlach, Jacobi and Prohaska');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_127','Reinger-Herzog');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_128','Kuvalis-Douglas');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_129','Koelpin LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_130','Willms Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_131','Wintheiser, Hahn and Goyette');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_132','Murazik, Trantow and Quitzon');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_133','Mertz LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_134','Thompson, Becker and Ernser');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_135','Schamberger Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_136','Effertz LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_137','Gibson, White and Kshlerin');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_138','Tremblay-Casper');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_139','Reinger Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_140','Blick Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_141','Rath, Braun and Walker');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_142','Labadie-Krajcik');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_143','McDermott, Weimann and Ferry');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_144','Beier-Leannon');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_145','Nienow, Oberbrunner and Bergstrom');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_146','Konopelski Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_147','Torp, Mann and Wolf');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_148','Schaden LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_149','Kovacek, Mertz and Boyle');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_150','Moen Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_151','Homenick, Smitham and Block');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_152','Hayes LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_153','Wisoky, Conroy and Kiehn');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_154','Littel, Veum and Greenfelder');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_155','Marvin-Champlin');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_156','Brown, Koepp and Green');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_157','Dicki-Kessler');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_158','Hyatt, Okuneva and Schroeder');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_159','Cormier Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_160','Runolfsdottir, Schuster and Kuhn');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_161','Schultz and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_162','Kozey, Purdy and Johnston');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_163','Muller-Schneider');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_164','Shields and Daughter');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_165','Mills LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_166','Orn Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_167','O''Keefe-Quigley');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_168','Leuschke, Jacobson and Boyle');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_169','Mann-Kautzer');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_170','Walsh-Towne');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_171','Rosenbaum-Kreiger');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_172','Kunze-Jacobi');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_173','Johnston, Batz and Schuppe');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_174','Lind-Buckridge');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_175','Flatley-Jacobi');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_176','Rau LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_177','Schmidt Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_178','Altenwerth Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_179','Harber Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_180','Cruickshank-McDermott');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_181','Johns, Casper and Hessel');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_182','Stiedemann, Ritchie and Watsica');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_183','Olson, Casper and Davis');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_184','Walsh, Gaylord and Cruickshank');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_185','Wyman, Thompson and Green');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_186','Hermiston and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_187','Frami, Murray and Marvin');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_188','Hessel and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_189','Gislason Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_190','McKenzie and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_191','Koss-Sipes');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_192','Macejkovic, Bashirian and Hane');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_193','Runolfsdottir, Nikolaus and Barton');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_194','Berge-Thompson');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_195','Turcotte-Krajcik');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_196','Beier Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_197','Grant and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_198','Bergnaum, Feeney and Orn');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_199','Hackett-Wintheiser');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_200','Berge, Balistreri and Price');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_201','Carroll LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_202','Stoltenberg and Daughters');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_203','Nader LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_204','Parisian-Bednar');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_205','Weber, Veum and Dach');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_206','Konopelski, Lesch and Keeling');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_207','Wilkinson Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_208','Schamberger, Grant and Keeling');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_209','Turcotte, Franecki and Cassin');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_210','Witting, Botsford and Crist');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_211','Farrell-Howe');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_212','Simonis, Hermann and Beatty');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_213','Zemlak-Macejkovic');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_214','Kohler, Torp and Kulas');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_215','Dickinson Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_216','Kuhlman Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_217','Borer-Jakubowski');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_218','Gulgowski-Will');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_219','Denesik LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_220','Williamson-Jacobi');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_221','Little, White and Kshlerin');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_222','Ferry-Treutel');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_223','Wisozk-Terry');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_224','Prohaska-Moen');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_225','Gleason-Bednar');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_226','Monahan-Schowalter');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_227','Bradtke, Weber and Ebert');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_228','Oberbrunner Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_229','McGlynn-Lakin');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_230','Gerhold-Wuckert');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_231','Weber and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_232','Kling, Schulist and Borer');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_233','Frami and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_234','Borer LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_235','Schamberger-Hilll');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_236','Wuckert LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_237','Prohaska and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_238','Volkman-Hagenes');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_239','Mitchell, Trantow and Lebsack');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_240','Jacobi-Blanda');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_241','Legros-Hirthe');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_242','Cummings-Ruecker');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_243','Kerluke, Douglas and Runolfsson');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_244','Gleichner, Roberts and O''Kon');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_245','Hand-Bauch');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_246','Barrows, Prosacco and Satterfield');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_247','Runolfsson-Cole');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_248','Kuphal, Olson and Kihn');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_249','Hegmann, Jerde and Hansen');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_250','Reinger LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_251','Medhurst-Koepp');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_252','Koch, Bins and Watsica');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_253','Reinger, Bruen and Dach');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_254','Strosin Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_255','Smitham and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_256','Little LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_257','Rohan-Rogahn');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_258','Armstrong-Schmeler');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_259','Bernier-Okuneva');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_260','Predovic Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_261','Jast, Stamm and Johnson');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_262','Farrell, Leannon and Frami');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_263','Legros-Rodriguez');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_264','Hand Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_265','Altenwerth-Will');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_266','Lang Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_267','Windler, Fisher and Kunze');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_268','Hettinger-Quigley');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_269','Harris, Kuhlman and Mertz');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_270','Wolff Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_271','Willms, Jaskolski and Nienow');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_272','Gutmann, Koelpin and Mitchell');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_273','Hintz LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_274','Hoeger-Fisher');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_275','Feeney Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_276','Zieme Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_277','Cormier, Balistreri and Okuneva');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_278','Osinski and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_279','Kassulke and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_280','Altenwerth-Abshire');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_281','Reynolds, Schmitt and Cummerata');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_282','Hudson-Romaguera');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_283','Yost LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_284','Bailey, Lebsack and Ebert');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_285','Herzog-Lynch');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_286','Howell, Lynch and Homenick');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_287','Hauck, Wyman and Beahan');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_288','McCullough and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_289','Beatty, Luettgen and Parker');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_290','Effertz-Mayert');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_291','Beahan-Funk');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_292','Quigley, Fahey and Bogan');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_293','Wolff, Boehm and Hirthe');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_294','Erdmaan Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_295','Koss Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_296','Lebsack-Ankunding');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_297','O''Connell, Kris and Ziemann');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_298','Maggio-Corkery');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_299','Lebsack Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_300','Botsford Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_301','Mueller-Turner');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_302','Weissnat, Hilll and Ritchie');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_303','Corkery, Grady and Waelchi');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_304','Zemlak-Collins');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_305','Ritchie and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_306','Nolan, Gibson and Davis');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_307','Rohan, Bosco and Huels');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_308','Heidenreich and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_309','Hahn-Gleichner');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_310','Turner-Labadie');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_311','Abshire, McClure and Konopelski');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_312','Cartwright Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_313','Schuppe Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_314','Brakus-Cummings');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_315','Mayert-Lang');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_316','Labadie-McKenzie');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_317','Boyer, West and Harris');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_318','Kreiger-Trantow');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_319','Morissette, Ryan and Legros');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_320','Hansen LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_321','Cassin, Medhurst and Feeney');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_322','Nicolas, Blanda and Hagenes');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_323','Kertzmann, Deckow and Robel');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_324','Emard, Weissnat and Hickle');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_325','Jacobs, Stracke and Mosciski');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_326','Hahn, Schamberger and Lindgren');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_327','Gerlach-Dooley');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_328','Kuvalis Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_329','Bailey-Kessler');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_330','Bernhard-Christiansen');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_331','Doyle, Hamill and Jacobi');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_332','Wunsch, Wunsch and Satterfield');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_333','Mayert, Hirthe and Littel');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_334','Wilderman LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_335','Herzog-Abshire');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_336','O''Connell and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_337','Bode and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_338','Orn, Stark and Wintheiser');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_339','Rutherford, Schneider and Herzog');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_340','Hirthe Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_341','Stamm-Wunsch');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_342','Zieme Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_343','Quigley LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_344','Stanton, Considine and Ferry');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_345','O''Kon Holdings');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_346','White, Spencer and Hilpert');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_347','Prohaska, Franecki and Spinka');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_348','Kuphal, Goyette and Runolfsdottir');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_349','Kihn-Williamson');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_350','Yost-Crooks');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_351','Lang-Lesch');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_352','Hoeger, Harber and Heaney');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_353','Corwin-Padberg');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_354','MacGyver-Ullrich');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_355','Ankunding-Yundt');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_356','Raynor-Deckow');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_357','Paucek-Weissnat');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_358','Reichel Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_359','Flatley-Rice');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_360','Conroy, Luettgen and Kris');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_361','Gottlieb, Bahringer and Kunze');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_362','Graham-Shields');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_363','Mayer LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_364','Reynolds and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_365','Stark, Armstrong and Graham');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_366','Crona, Reichel and Abernathy');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_367','O''Keefe-Murazik');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_368','Klein Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_369','Rippin Holdings');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_370','Rath, Considine and Quigley');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_371','Turcotte and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_372','Mayer Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_373','Green-Leuschke');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_374','Keebler and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_375','Crooks, McClure and O''Keefe');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_376','Muller, Nader and Windler');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_377','Lind, McKenzie and Zemlak');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_378','Ritchie, Brekke and Smith');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_379','Gibson, Wyman and Sawayn');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_380','Bogan, Okuneva and Kovacek');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_381','Lindgren Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_382','Gislason-Powlowski');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_383','O''Kon Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_384','Ledner LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_385','Altenwerth-Langosh');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_386','Rippin Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_387','Cole Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_388','Mueller-Legros');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_389','Crooks-Brakus');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_390','Bailey Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_391','Brekke Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_392','Tromp-Mohr');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_393','Bechtelar and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_394','Bradtke-Terry');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_395','Erdman Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_396','Kreiger-Moen');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_397','Schultz Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_398','Wintheiser Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_399','Schamberger, Marvin and Rutherford');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_400','Bayer-Beer');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_401','Shields and Children');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_402','Rippin, Wunsch and Bode');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_403','Cartwright, Raynor and Koss');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_404','Medhurst-Cartwright');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_405','Johnson LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_406','Larkin-Cummings');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_407','Collins, Dach and Robel');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_408','Nikolaus LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_409','Ankunding Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_410','Sipes-Shanahan');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_411','Rogahn Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_412','Smith-Adams');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_413','Lemke, Okuneva and Cormier');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_414','Moore and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_415','Kiehn, Stiedemann and Littel');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_416','Considine, Schulist and Russel');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_417','Harber-Collins');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_418','Haley, Anderson and Cummings');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_419','Champlin and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_420','Grady, Weissnat and Gerlach');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_421','Heathcote-Dibbert');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_422','Stanton Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_423','Gorczany LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_424','Schmidt, Dietrich and Schinner');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_425','West, Jones and Heidenreich');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_426','Runte-Lowe');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_427','Grimes-Reilly');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_428','Streich, Feil and Batz');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_429','Kshlerin-McLaughlin');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_430','Thompson-McGlynn');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_431','Herman-Sporer');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_432','Upton-Huels');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_433','Hilll, Goldner and Kessler');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_434','Turner and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_435','Johnston and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_436','Zemlak, Hayes and Feil');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_437','Nolan, Mohr and Blick');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_438','Weber, Conroy and Fay');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_439','Dickinson, Fisher and Padberg');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_440','Huel-Rippin');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_441','Carter and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_442','Kub, Pagac and Gutkowski');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_443','Abbott-Leannon');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_444','Becker-McLaughlin');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_445','Rohan-Spencer');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_446','Hickle Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_447','Williamson-Hartmann');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_448','Marks-Kuhn');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_449','Durgan-Haag');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_450','Green-Pollich');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_451','Marvin, Wintheiser and Schaefer');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_452','Hegmann Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_453','McDermott, Bernier and Leuschke');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_454','Turner-Pouros');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_455','Gerhold LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_456','Hansen Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_457','Schaefer-Hoppe');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_458','Von Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_459','Bahringer-Quitzon');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_460','Greenholt-Conroy');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_461','Fritsch-Cruickshank');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_462','Purdy Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_463','Reichert Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_464','Franecki-Veum');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_465','Corwin, Schoen and Torphy');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_466','Jaskolski and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_467','Braun-Borer');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_468','Predovic-Kerluke');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_469','McGlynn Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_470','Hilll-Grady');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_471','Mitchell and Sons');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_472','Bashirian Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_473','Hahn Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_474','Zemlak-O''Hara');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_475','Kessler Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_476','Kilback, Harvey and Corwin');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_477','Keeling, Romaguera and Schuster');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_478','Lueilwitz, Kilback and Sawayn');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_479','Cormier, Brakus and Lehner');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_480','Hirthe LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_481','Medhurst, Flatley and Rempel');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_482','Greenfelder LLC');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_483','Veum, Steuber and Friesen');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_484','Smitham, Lesch and Padberg');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_485','Jacobs-Wiza');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_486','O''Kon-Cummings');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_487','Bergnaum, Dicki and Cormier');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_488','Schmidt-Rowe');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_489','Deckow-Braun');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_490','Gutmann, Paucek and Barton');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_491','Crist, Morar and Block');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_492','Stroman, Legros and Towne');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_493','Johnson Group');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_494','Adams Inc');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_495','Torp-Bailey');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_496','Gerhold-Kiehn');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_497','Sanford, Streich and O''Conner');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_498','Cole, Gottlieb and Klocko');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_499','Kohler-Hauck');
INSERT INTO Shop(Shop_id,name) VALUES ('SHOP_500','Bogan Inc');
